---
title: "11/19 Class"
author: "Emily Axelsen"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(skimr)
library(fs)
```

```{r, cache = TRUE}
# Download zipped files from the internet because there are so many files
download.file("https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip", destfile = "master.zip")

# Unzip files
unzip("master.zip")

# Read in one data set from the data folder
raw1 <- read_csv("2018-live-poll-results-master/data/elections-poll-az02-1.csv", col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")
))
```


```{r}
# Read in all files from data folder
my_list <- fs::dir_ls("2018-live-poll-results-master/data/")

# Read in all of the files
raw <- map_dfr(my_list, .id = "source", read_csv, col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = "")))
```



```{r}
# Create data set to compare democratic votes with female identification
x <- raw %>%
  mutate(dvote = ifelse(response == "Dem", 1, 0)) %>%
  mutate(female = ifelse(gender == "Female", 1, 0)) %>% 
  select(dvote, female, response, gender)

# Create plot to depict relationship between female and dvote
x %>% 
  ggplot(aes(x = female, y = dvote)) +
  geom_jitter(alpha = 0.05)

# glm is a logistic model 
glm.obj <- glm(dvote ~ female, data = x, family = "binomial")

# Fake new data set to test our model on
my_data <- tibble(female = c(0, 0, 1))

# How can I use the model with new data?
model <- predict(glm.obj, newdata = my_data, type = "response")

# Add the prediction for each value in our current to test the model
model_predict <- x %>%
  mutate(prediction = predict(glm.obj, type = "response"))

```








